### ISSUE TITLE
pkg-config-rs doesn't see available libraries in msys2

### ISSUE THREAD

**Issue by o01eg** [alexcrichton/pkg-config-rs#12]
When I check if library presents in the system I get correct result.
```
$ pkg-config --libs --cflags cairo ; echo $?
-mms-bitfields -I/mingw64/include/cairo -I/mingw64/include/glib-2.0 -I/mingw64/lib/glib-2.0/include -I/mingw64/include/pixman-1 -I/mingw64/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/freetype2 -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include/libpng16 -IC:/msys64/mingw64/include/harfbuzz -I/mingw64/include -I/mingw64/include/freetype2 -I/mingw64/include -I/mingw64/include/harfbuzz -I/mingw64/include/libpng16 -L/mingw64/lib -LC:/msys64/mingw64/lib/../lib -L/mingw64/lib -LC:/msys64/mingw64/lib -L/mingw64/lib -lcairo -lz -lgobject-2.0 -lffi -lglib-2.0 -lintl -pthread -lws2_32 -lole32 -lwinmm -lshlwapi -lintl -lpixman-1 -lfontconfig -lexpat -lfreetype -lexpat -lfreetype -lz -lbz2 -lharfbuzz -lpng16 -lz
0
```

But if I try to use it from rust with test code:
```rust
extern crate "pkg-config" as pkg_config;

fn main() {
	println!("{:?}", pkg_config::find_library("cairo"));
}
```

I get only.
```
Err("`\"pkg-config\" \"--libs\" \"--cflags\" \"cairo\"` did not exit successfully: exit code: 1\n--- stderr\nPackage cairo was not found in the pkg-config search path.\nPerhaps you should add the directory containing `cairo.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'cairo\' found\n")
```

PKG_CONFIG_PATH is "/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig"
rustc 1.0.0-dev (e98e39133 2015-03-20) (built 2015-03-20)

**Comment by alexcrichton** [comment]
Could this perhaps be a difference on how you're running it in Rust vs how you're running it in a shell? How did you run the code in Rust?

**Comment by o01eg** [comment]
I use Cargo.toml and `cargo run`
```
[package]
name = "pkgctest000"
version = "0.0.1"

[dependencies]
pkg-config = "*"
```

**Comment by o01eg** [comment]
It looks like application get `PKG_CONFIG_PATH="E:\msys64\mingw64\lib\pkgconfig;E:\msys64\mingw64\share\pkgconfig"` and pkg-config shows different libraries with unix path and windows path.

**Comment by o01eg** [comment]
It looks like msys2 bug: https://sourceforge.net/p/msys2/tickets/143/

**Comment by alexcrichton** [comment]
Aha, thanks for investigating!

**Comment by o01eg** [comment]
There should be used `mingw-w64-x86_64-pkg-config` or its 32-bit version instead `pkg-config`.

**Comment by mingwandroid** [comment]
Indeed, `pkg-config` is for building msys2 (Cygwin-like) software, not native (MinGW-w64) software.

**Comment by Globik** [comment]
And for what should be using msys2 software?

**Comment by mingwandroid** [comment]
Mostly for building native MinGW-w64 software.
