### ISSUE TITLE
error: can't find crate for `pkg_config`

### ISSUE THREAD

**Issue by manuels** [alexcrichton/pkg-config-rs#13]
Looks like there is a bug in with the lastest version of pkg-config. I'm using `rustc 1.0.0-nightly (123a754cb 2015-03-24) (built 2015-03-25)` and running `cargo test` raises an error:

    $ git clone https://github.com/alexcrichton/pkg-config-rs.git
    $ cd pkg-config-rs
    $ cargo build # works fine
       Compiling pkg-config v0.3.2 (file:///tmp/pkg-config-rs)
    $ cargo test # fails
       Compiling pkg-config v0.3.2 (file:///tmp/pkg-config-rs)
    tests/disabled.rs:3:14: 3:26 warning: obsolete syntax: "crate-name"
    tests/disabled.rs:3 extern crate "pkg-config" as pkg_config;
                                     ^~~~~~~~~~~~
    note: use an identifier not in quotes instead
    tests/disabled.rs:3:1: 3:41 warning: crate names soon cannot contain hyphens: pkg-config
    tests/disabled.rs:3 extern crate "pkg-config" as pkg_config;
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    tests/disabled.rs:3:1: 3:41 error: can't find crate for `pkg_config`
    tests/disabled.rs:3 extern crate "pkg-config" as pkg_config;
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    error: aborting due to previous error
    Could not compile `pkg-config`.
    
    To learn more, run the command again with --verbose.

Do you have a clue what's going on here? This error is also raised for **any** crates depending on pkg-config.

**Comment by gkoz** [comment]
The error message suggests you use `extern crate pkg_config` because dashes in crate names aren't allowed anymore.

**Comment by manuels** [comment]
the error message is a bit misleading because it's a warning message actually.
Anyway, thanks!
