### ISSUE TITLE
Provide the version number

### ISSUE THREAD

**Issue by IvanUkhov** [alexcrichton/pkg-config-rs#17]
I’m wondering if it could be a useful feature to provide the version number of the requested library (if found), that is, to provide the output of `pkg-config --modversion`. I have a use case for that, but I’m not sure if it’s of general interest. For instance, one could imagine enabling/disabling certain features depending on the available version. Thank you.

Regards,
Ivan

**Comment by alexcrichton** [comment]
Certainly! I'm fine with adding whatever flags are necessary :)

**Comment by alexcrichton** [comment]
Fixed in https://github.com/alexcrichton/pkg-config-rs/pull/18
