### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by alexreg** [alexcrichton/pkg-config-rs#25]
`pkg_config::Config::statik` should be `pkg_config::Config::static`

...unless this is deliberate, for some reason?

**Comment by alexcrichton** [comment]
Yeah unfortunately `static` is a keyword in Rust, so I had to pick the next best thing :)

**Comment by alexreg** [comment]
Ah, I didn’t know being a keyword prevented it from being a function name. Fair enough. :)
