### ISSUE TITLE
Allow pkg-config checks to be skipped in CI environments that don't use or care about linking

### ISSUE THREAD

**Issue by SnirkImmington** [alexcrichton/pkg-config-rs#29]
I have a project with a dependency which uses pkg-config. The dependency's build script matches your suggestion in the readme:
```rust
fn main() {
    pkg_config::probe_library("somelibrary").unwrap();
}
```

I am running tests with Travis CI using their docker infrastructure. I have ensured the dependency and executable `pkg-config` are installed in the container. 
However, when compiling my project the CI builds fail because pkg-config can't find the library this dependency requests. The pkg-config crate-level docs suggest setting `$FOO_NO_PKG_CONFIG` but this will just fail the builds "faster" as the `unwrap()` will still panic.

I could file an issue with this dependency, or look into installing `pkg-config` on Travis, or file an issue about supporting Travis CI specifically. However, given the existence of the `*_NO_PKG_CONFIG` I figured you wouldn't be opposed to `*_SKIP_PKG_CONFIG`, which would be more fine-grained - I am using the workaround `export PKG_CONFIG=echo` (which is also not in the documentation) to prevent pkg-config from running at all in the CI environment.

Let me know what you think and I can open a PR.

**Comment by alexcrichton** [comment]
Thanks for the report! I'm a little confused though as `*_NO_PKG_CONFIG` *should* skip everything related to `pkg-config` and return quickly, but is that not the case?

**Comment by SnirkImmington** [comment]
The issue is that it causes `pobe_libary` to return an `Err`, which panics when it hits `unwrap` and will prevent Cargo from building the dependency entirely.

**Comment by gkoz** [comment]
The build script in question clearly isn't prepared to manage without `pkg-config` (I believe `_NO_PKG_CONFIG` is meant to cause the script to build the library from source). Skipping it would just leave the linker unable to find the library.

> However, when compiling my project the CI builds fail because pkg-config can't find the library this dependency requests.

Perhaps this specific issue can be solved instead? Could you link to the relevant Travis log?

**Comment by alexcrichton** [comment]
@SnirkImmington ah but the `Err` could be ignored, right? That is, if you drop it, then nothing panics?

**Comment by SnirkImmington** [comment]
> @SnirkImmington ah but the `Err` could be ignored, right? That is, if you drop it, then nothing panics?

I don't think I'm being clear here. This is not my build script. This is not my code. A dependency that someone else wrote is causing my builds to fail, and I have to hack on my CI build environment so my project can start compiling. This dependency's build script is "hard coded" to `unwrap` this error.

The underlying concern I'm feeling here is lack of control over the build process. This is, of course, something that happens when dependencies can have build scripts at all, but I didn't want to _rewrite_ this dependency's build script. I spent a few commits trying to fix some environment variable that the error message hinted might be the cause.

> Perhaps this specific issue can be solved instead? Could you link to the relevant Travis log?

I think it would be a waste of both of our time to look at logs and suggest different values for `$PKG_CONFIG_PATH`. If you don't think these changes are a good idea, I can close this issue and continue using my workaround.

> Skipping it would just leave the linker unable to find the library.

This isn't always the priority in build environments. Even if our dependencies weren't able to find a dynamic linked library when we built them, we'd get the linker error immediately after when we run tests. This could be used to make sure that the Rust code of a library with specific C bindings can _compile_, without installing C libraries, setting up `pkg-config`, or running any tests that would immediately cause a linker fail.

I'm also pretty sure that running `cargo doc` in CI scripts to update docs shouldn't care about C bindings. What about creating binary releases? It shouldn't matter if the dynamic libs aren't in the build environment at that time that we build them. I just think this is a lot of forcing of others' code and requirements into the developer's environment, which the developer could have reasons to ignore. 

I'm sure if you looked around at other Rust projects that have this issue, they've taken similar solutions - modifying the build scripts of their dependencies programmatically in CI, or removing the `build.rs` files altogether. We don't want to open PRs against all our dependencies or maintain forks just so our code can build.

**Comment by alexcrichton** [comment]
Cargo was designed to be pretty flexible around linking to native libraries, so you can use some of its escape hatches as well. For example if a `links` key is specified then you can override the build script entirely and just supply a pre-built copy. 

I'd be pretty hesitant to add a configuration which forces pkg-config to "lie" that the dependency has been found when it actually hasn't, unfortunately. In general build scripts need to be robust if they intend to be used in lots of situations like this, so it may also be quite useful to upstream the build script changes you made perhaps?

**Comment by SnirkImmington** [comment]
> I'd be pretty hesitant to add a configuration which forces pkg-config to "lie" that the dependency has been found when it actually hasn't, unfortunately

Okay, that's a fair call. Cargo provides some nice hooks for linking, and can keep using the value of `$PKG_CONFIG` if necessary.
