### ISSUE TITLE
rustc 1.14.0 complains about "#![feature(path)]" error[E0554]: #[feature] may not be used on the stable release channel

### ISSUE THREAD

**Issue by daym** [alexcrichton/pkg-config-rs#33]
I'm trying to package rust-pkg-config (ha!) for the GNU Guix distribution but I get the following error message (using rustc 1.14.0):

error[E0554]: #[feature] may not be used on the stable release channel

What should I do?

**Comment by alexcrichton** [comment]
Seems odd! This library doesn't use any features, though, so you may have been using an ancient historical version.

**Comment by daym** [comment]
It was 0.3.1.

**Comment by alexcrichton** [comment]
Ah ok, in that case if you update it should fix this issue

**Comment by daym** [comment]
Seems that it depends on lazy_static, which depends on spin. spin then fails.

```
6 | #![cfg_attr(feature = "asm", feature(asm))]
  |                              ^^^^^^^^^^^^

error[E0554]: #[feature] may not be used on the stable release channel
 --> src/lib.rs:7:42
  |
7 | #![cfg_attr(feature = "core_intrinsics", feature(core_intrinsics))]
  |                                          ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #[feature] may not be used on the stable release channel
 --> src/lib.rs:8:35
  |
8 | #![cfg_attr(feature = "const_fn", feature(const_fn))]
  |                                   ^^^^^^^^^^^^^^^^^

```

**Comment by alexcrichton** [comment]
Some other crate is likely enabling the relevant feature in the lazy-static crate, which causes *all* crates to end up using it.

**Comment by daym** [comment]
The lazy_static chroot contains the following crates: lazy_static.

Network access is disabled.

Running `cargo build` then says that.

It seems that lazy_static has provisions for just using std::sync::Once if nightly and not spin_no_std. However, (1) it doesn't use that and (2) we have a non-nightly rustc (1.14.0) and the module std::sync::Once already exists. Is lazy_static already in rustc, too?
