### ISSUE TITLE
statik(true) doesn't do anything on macOS

### ISSUE THREAD

**Issue by pornel** [alexcrichton/pkg-config-rs#38]
In macOS passing `--static` to pkg-config is not enough to get the library linked statically. For almost all packages both `.a` and `.dylib` exist, and names specified by pkg-config are ambiguous.

```sh
$ pkg-config --static --libs lcms2
-L/usr/local/Cellar/little-cms2/2.8/lib -llcms2 -lm
$ pkg-config --libs lcms2
-L/usr/local/Cellar/little-cms2/2.8/lib -llcms2
```

Instructions printed by pkg-config *don't* specify that static linking was requested:

> cargo:rustc-link-search=native=/usr/local/Cellar/little-cms2/2.8/lib
cargo:rustc-link-lib=lcms2
cargo:rustc-link-lib=m

So rustc invocation switches to dynamic linking:

>  Running `rustc `…` -l z -l lcms2 -l m`…

```sh
otool -L target/release/test
    /usr/local/opt/little-cms2/lib/liblcms2.2.dylib (compatibility version 3.0.0, current version 3.8.0)
```

I think this library should be printing `rustc-link-lib=static=lcms2` when `.statik(true)` was specified (but only for the probed library, e.g. don't statically link libz if libpng was probed)

**Comment by alexcrichton** [comment]
This is likely because the contents of /usr are considered to be part of the system and always preferred to link dynamically rather than statically. https://github.com/alexcrichton/pkg-config-rs/pull/37 may be related?

**Comment by pornel** [comment]
Yes, `is_system` is definitely wrong for macOS. System libraries are in `/System/Library/` and `/usr/lib`.

But `/usr/local/{lib,opt}` is used by 3rd party homebrew.

**Comment by alexcrichton** [comment]
Seems reasonable to patch! Want to send a PR?
