### ISSUE TITLE
Version checking is broken

### ISSUE THREAD

**Issue by Florob** [alexcrichton/pkg-config-rs#4]
The command line parameters used to check for a minimal library version are not actually legal:
```
% pkg-config --libs --atleast-version="0.21.0" libgit2
Ignoring incompatible output option "--atleast-version"
-lgit2
```

One possible fix would be to rewrite the call to:
```
% pkg-config --libs "libgit2 >= 0.21.0"
-lgit2
```

Alternatively a separate function could be provided, to check for a libraries existence.

**Comment by alexcrichton** [comment]
Interesting, what version of `pkg-config` do you have? For me it looks like:

```
$ pkg-config --help
Usage: pkg-config [OPTION...]                                                                                       
      ...
      --atleast-version=VERSION               return 0 if the module is at least version VERSION                    
      ...

$ pkg-config --version
0.26
```

**Comment by Florob** [comment]
Interesting indeed. This is with `pkg-config` version 0.28. I didn't expect that to be a recent change.
Indeed my `--help` and man page says the same thing as yours, but the tool behaves as though the whole bunch of `--exists`, `--atleast-version=VERSION`, `--exact-version=VERSION`, and `--max-version=VERSION` are to be used on their own. Possibly the syntax I mentioned above is now preferred, because anything else is not workable when checking for multiple libraries at the same time, but for now that's a wild guess.

**Comment by Florob** [comment]
Okay, so I have investigated a bit more. Apparently `--exists` is the default output mode and can be mixed with `--{atleast,exact,max}-version`, but only one of them. Any other output mode option (`--libs`, `--cflags`, etc.) does not work in conjunction with them. Indeed the change is not exactly recent (2012), but within the 0.28 time frame. The exact commit is http://cgit.freedesktop.org/pkg-config/commit/?id=548ba5b223b28370f1ebad51dd7ae298e4be1428 and was regarded as a bug fix.

**Comment by alexcrichton** [comment]
Very interesting! Thanks for investigating :)

I've pushed a fix which uses the new syntax now.
