### ISSUE TITLE
Yank all broken pkg-config versions from crates.io

### ISSUE THREAD

**Issue by klausi** [alexcrichton/pkg-config-rs#62]
On https://crates.io/crates/pkg-config/versions everything below v0.3.2 does not compile with recent Rust versions. They should all be yanked so that cargo only installs working minimal versions.

**Comment by alexcrichton** [comment]
Thanks for the report! I [commented over on the Cargo PR](https://github.com/rust-lang/cargo/pull/5275#issuecomment-377965911) though in that I don't think this is quite the right solution, so I'm going to close this.

**Comment by kornelski** [comment]
This is still an ecosystem-wide problem. It's relatively common for crates to [specify `pkg-config = "0.3"`](https://lib.rs/crates/pkg-config/rev), and this breaks min-versions.

Inability to rely on min-versions causes headaches with maintaining [MSRV](https://lib.rs/stats#rustc). For example users or `zeroize` resort to [requiring `>=1, <1.4` or `=1.3`](https://lib.rs/crates/zeroize/rev).
