### ISSUE TITLE
Specify minimal required Rust version

### ISSUE THREAD

**Issue by dbrgn** [alexcrichton/pkg-config-rs#64]
The pkg-config 0.3.10 update broke downstream crates on Rust 1.21...

```
error[E0599]: no method named `to_ascii_uppercase` found for type `char` in the current scope
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/pkg-config-0.3.10/src/lib.rs:538:28
    |
538 |     name.chars().map(|c| c.to_ascii_uppercase()).map(|c| {
    |                            ^^^^^^^^^^^^^^^^^^
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
            candidate #1: `use std::ascii::AsciiExt;`
```

I run cargo-audit in CI for most of my crates, which depends on pkg-config (directly or indirectly). Unfortunately this means that I cannot use cargo-audit in CI for crates supporting Rust 1.21 without adding a separate build step that runs on a newer version.

Would it be possible to specify the minimal required Rust version, to add that version to CI and to consider changes to the minimal version a breaking change?

**Comment by alexcrichton** [comment]
Oops sorry about that, PRs are of course welcome to tweak and fix this!
