### ISSUE TITLE
Accept '-F' and '-framework' flags

### ISSUE THREAD

**Issue by jonasp** [alexcrichton/pkg-config-rs#7]
For OS X `-F` and `-framework` flags need to be accepted and translated into into `-L framework=...`  and `-l framework=...`, respectively.

The `-F` option needs to be added to `rustc` before, see [rust-lang/rust/#20259](https://github.com/rust-lang/rust/issues/20259).

**Comment by alexcrichton** [comment]
Do you have an example of a `pkg-config` file which prints out `-F` or `-framework`? Just something to test out on.

**Comment by jonasp** [comment]
Sure, I encountered this with the Qt5 packages I installed with homebrew.

```
$ pkg-config --libs Qt5Core
-F/usr/local/Cellar/qt5/5.4.0/lib -framework QtCore
```
