### ISSUE TITLE
Support exact_version

### ISSUE THREAD

**Issue by Hakuyume** [alexcrichton/pkg-config-rs#74]
`pkg-config` provides `name = version` syntax to specify the exact version. It would be nice to add a wrapper for this functionality.  Although `pkg_config::probe_library("name = version")` works, I think it is abuse.

**Comment by sdroege** [comment]
What API do you suggest for this? Something like `Config::atleast_version()`, a `Config::exact_version()`?

**Comment by sdroege** [comment]
Would in any case be easy to add, as well as a `name >= version_min, name < version_max` kind of check

**Comment by Hakuyume** [comment]
I was thinking `Config::exact_version()`. Taking `(min, max)` is also ok.

**Comment by sdroege** [comment]
I was thinking of both. Do you want to try your luck adding this? Otherwise I'll add it somewhere on my list but it might take a while until I get to it

**Comment by Hakuyume** [comment]
OK, I'll try.

**Comment by sdroege** [comment]
Awesome! If you get stuck somewhere and need help, feel free to ask here, or if you want me to take over :)

**Comment by Hakuyume** [comment]
@sdroege  I made a PR (#75). Could you review it?
