### ISSUE TITLE
Provide something to perform include directory lookups

### ISSUE THREAD

**Issue by sfackler** [alexcrichton/pkg-config-rs#8]
It's sometimes necessary to write gross C shims to deal with libraries, and it'd be nice for pkg-query to be able to pull the include paths for gcc-rs.

https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/src/old_openssl_shim.c
https://github.com/sfackler/rust-openssl/blob/6ef819f9718c3b43551461b72c531c2eeee878f9/openssl-sys/build.rs#L39-L50

**Comment by alexcrichton** [comment]
Would returning the results in a struct instead of `()` as part of `find` work ok?

**Comment by sfackler** [comment]
That should work. There aren't any cases where you wouldn't want to emit the `cargo:rustc-flags` for the package, right?
